# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  db:
    image: postgres:16-alpine
    ports:
      - ${DB_PORT:-}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    env_file: .env

  backend:
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${BACKEND_PORT:-}:8000
    build:
      context: backend
      dockerfile: Dockerfile
      target: development
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          initial_sync: true
        - path: ./backend/pyproject.toml
          action: rebuild
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432
    env_file: .env
    restart: unless-stopped

  frontend:
    depends_on:
      - backend
    ports:
      - ${FRONTEND_PORT:-}:5173
    build:
      context: frontend
      dockerfile: Dockerfile
      target: development
    develop:
      watch:
        - path: ./frontend
          action: sync
          target: /app
          initial_sync: true
        - path: ./frontend/package.json
          action: rebuild
    env_file: .env
    restart: unless-stopped

volumes:
  pgdata:
