"""update schema

Revision ID: d0951deb73f1
Revises: 199c025a96c9
Create Date: 2026-05-28 18:04:23.956381

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0951deb73f1"
down_revision: Union[str, Sequence[str], None] = "199c025a96c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_item_status_name", "item_status", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_item_status_name", "item_status", type_="unique")
    # ### end Alembic commands ###
